# Generated by Django 5.0.1 on 2024-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
